# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: echo "$GITHUB_CONTEXT"
      
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=1.0.0 --no-build --output .
#     - name: Upload Artifact GitHub Action
#       uses: actions/upload-artifact@v2
#       with: 
#         name: assets-for-download-1.0
#         path: README.md
#     - uses: actions/download-artifact@v3
#       id: download
#       with:
#         name: 'assets-for-download'
#         path: tmp\README.md 
    - name: NuGet Push
      #run: dotnet nuget push "bin/Release/dotnet-core-api.1.0.0.nupkg"  --api-key https://github.com/123patilmayuri/dotnet-core-api 
      run: dotnet nuget add source --username 123patilmayuri --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/123patilmayuri/dotnet-core-api/index.json"

#     - name: publish 
#       run: dotnet new console --name dotnet-core-api && dotnet pack --configuration Release && dotnet nuget push "bin/Release/dotnet-core-api.1.0.0.nupkg"  --api-key https://github.com/123patilmayuri/dotnet-core-api --source "github"
        
        
